# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='severity',
            field=models.SmallIntegerField(choices=[(1, 'Low'), (2, 'High'), (3, 'Medium'), (4, 'Trivial'), (5, 'Critical')], default=3, verbose_name='severity'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='state',
            field=models.SmallIntegerField(choices=[(1, 'Open'), (2, 'Closed'), (3, 'Assigned')], default=1, verbose_name='state'),
        ),
    ]
