# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20151208_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='severity',
            field=models.SmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Trivial'), (5, 'Critical')], default=2, verbose_name='severity'),
        ),
    ]
